// _data/projects.js
export default [
  {
    name: "Chess",
    githubUrl: "https://github.com/cbloodsworth/Chess",
    imageUrl: "/assets/img/projects/Chess.png",
    altText: "chess",
    description: "The original two-player game. Made in C++ and uses SFML for visuals.",
    gridRow: 1,
    gridColumn: 1,
  },
  {
    name: "Image Processor",
    imageUrl: "/assets/img/projects/Image_Processor.png",
    altText: "image processor",
    description: "Takes in various .tga files and combines / manipulates them. Made in C++",
    gridRow: 1,
    gridColumn: 2,
  },
  {
    name: "Discover Delays",
    githubUrl: "https://github.com/cbloodsworth/DiscoverDelays",
    imageUrl: "/assets/img/projects/DiscoverDelays.png",
    altText: "flight data viewing client",
    description: "Takes in a .csv with flight info, sorts the data and displays it. Made in C++ and uses SFML for visuals.",
    gridRow: 2,
    gridColumn: 1,
  },
  {
    name: "ARM Disassembler",
    imageUrl: "/assets/img/projects/ARM_Disassembler.png",
    altText: "binary to ARM",
    description: "Takes in binary machine code and outputs the equivalent ARMv8 instructions, then executes them. Made in C++.",
    gridRow: 2,
    gridColumn: 2,
  },
  {
    name: "Gator Raider",
    imageUrl: "/assets/img/projects/GatorRaider.png",
    altText: "pacman game with code in background",
    description: "Developed a bot for a pre-made Ms. Pacman clone that attempts to get the most points possible. Made in Java.",
    gridRow: 3,
    gridColumn: 1,
  },
  {
    name: "Portfolio Site",
    githubUrl: "https://github.com/cbloodsworth/cbloodsworth.github.io",
    imageUrl: "/assets/img/projects/portfolio.png",
    blogUrl: "/projects/portfolio-site",
    altText: "portfolio site",
    description: "Developed a personal portfolio website in HTML/CSS. You're on it right now!",
    gridRow: 3,
    gridColumn: 2,
  },
  {
    name: "Swamp Investigator",
    githubUrl: "https://github.com/cbloodsworth/SwampInvestigator",
    imageUrl: "/assets/img/projects/swamp_investigator.png",
    altText: "swamp investigator exploration game",
    description: "Procedurally generated exploration game made in Python using the PyGame framework.",
    gridRow: 4,
    gridColumn: 1,
  },
  {
    name: "PLC Interpreter",
    imageUrl: "/assets/img/projects/plc_interpreter.png",
    altText: "plc interpreter to java programming language",
    description: 'Interpreter from a made-up language to Java. Parses "PLC language" code, produces valid and compilable Java code.',
    gridRow: 4,
    gridColumn: 2,
  },
];